package com.csye6225.spring2020.courseservice2.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Announcement")
public class Announcement {
private String announcementId;
private String id;
private String announcementText;
private String boardId;

public Announcement() {
	
}

public Announcement(String announcementId,String announcementText,String boardId ) {
	this.announcementId = announcementId;
	this.announcementText = announcementText;
	this.boardId = boardId;
	
}
@DynamoDBHashKey(attributeName="announcementId")
@DynamoDBAutoGeneratedKey
public String getAnnouncementId() {
	return announcementId;
}

public void setAnnouncementId(String announcementId) {
	this.announcementId = announcementId;
}
@DynamoDBAttribute(attributeName = "id")
public String getId() {
	return id;
}

public void setId(String id) {
	this.id = id;
}
@DynamoDBAttribute(attributeName = "announcementText")
public String getAnnouncementText() {
	return announcementText;
}

public void setAnnouncementText(String announcementText) {
	this.announcementText = announcementText;
}
@DynamoDBAttribute(attributeName = "boardId")
public String getBoardId() {
	return boardId;
}

public void setBoardId(String boardId) {
	this.boardId = boardId;
}

}
