package com.csye6225.spring2020.courseservice2.Model;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName="Course")
public class Course {
	private String courseId;
	private String id;
	private String name;
	private List<String>enrolledStudents;
	private List<String> lectureId;
    private String professorId;
	private String boardId;
	private String courseSNSTopic;
	
	public Course() {
		
	}
	public Course(String id,String name,String professorId,List<String>enrolledStudents,List<String>lectureId,
			String boardId, String courseSNSTopic) {
		this.id = id;
		this.name= name;
		this.enrolledStudents = enrolledStudents;
		this.lectureId = lectureId;
		this.professorId = professorId;
		this.boardId = boardId;
		this.setCourseSNSTopic(courseSNSTopic);
	}
	@DynamoDBHashKey(attributeName="courseId")
	@DynamoDBAutoGeneratedKey
	public String getCourseId() {
		return courseId;
	}
	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}
	@DynamoDBAttribute(attributeName = "profId")
	public String getprofessorId() {
		return professorId;
	}
	public void setprofessorId(String professorId) {
		this.professorId = professorId;
	}
	@DynamoDBAttribute(attributeName = "boardId")
	public String getBoardId() {
		return boardId;
	}
	
	public void setBoardId(String boardId) {
		this.boardId = boardId;
	}
	@DynamoDBAttribute(attributeName = "snsTopic")
	public String getCourseSNSTopic() {
		return courseSNSTopic;
	}
	public void setCourseSNSTopic(String courseSNSTopic) {
		this.courseSNSTopic = courseSNSTopic;
	}
	@DynamoDBAttribute(attributeName = "id")
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBAttribute(attributeName = "courseName")
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	@DynamoDBAttribute(attributeName = "enrolledStudents")
	public List<String> getEnrolledStudents() {
		if (enrolledStudents == null) {
			enrolledStudents = new ArrayList();
		}
		return enrolledStudents;
	}
	public void setEnrolledStudents(List<String> enrolledStudents) {
		this.enrolledStudents = enrolledStudents;
	}
	@DynamoDBAttribute(attributeName = "lectureId")
	public List<String> getLectureId() {
		if(lectureId == null) {
			lectureId = new ArrayList();
		}
		return lectureId;
	}
	public void setLectureId(List<String> lectureId) {
		this.lectureId = lectureId;
	}
}
