package com.csye6225.spring2020.courseservice2.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Lecture")
public class Lecture {
	private String LectId;
	private String notes;
	private String materials;
    private String lectureId;
    private String courseName;
	
	public Lecture() {
		
	}
	public Lecture(String lectureId, String notes,String materials,String courseName) {
		this.lectureId = lectureId;
		this.notes = notes;
		this.materials = materials;
		this.courseName = courseName;
	}
	@DynamoDBHashKey(attributeName="LectId")
	@DynamoDBAutoGeneratedKey
	public String getLectId() {
		return LectId;
	}
	public void setLectId(String lectId) {
		LectId = lectId;
	}
	@DynamoDBAttribute(attributeName = "courseName")
	public String getCourseName() {
		return courseName;
	}
	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}
	@DynamoDBAttribute(attributeName = "id")
	public String getLectureId() {
		return lectureId;
	}
	public void setLectureId(String lectureId) {
		this.lectureId = lectureId;
	}
	@DynamoDBAttribute(attributeName = "notes")
	public String getNotes() {
		return notes;
	}
	public void setNotes(String notes) {
		this.notes = notes;
	}
	@DynamoDBAttribute(attributeName = "materials")
	public String getMaterials() {
		return materials;
	}
	public void setMaterials(String materials) {
		this.materials = materials;
	}
}
