package com.csye6225.spring2020.courseservice2.Model;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName="professor")
public class Professor {

	private String id;
   
    private String profId;
	
	private String firstName;

	private String lastName;

	private String department;

    private String joiningDate;

	public Professor() {
	}

	public Professor(String firstName, String lastName,String department) {
		this.id = firstName+lastName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.department = department;
	}
	@DynamoDBAttribute(attributeName = "id")
	public String getId() {
		return firstName+lastName;
	}

	public void setId(String id) {
		this.id = firstName+lastName;
	}
	@DynamoDBHashKey(attributeName="profId")
	@DynamoDBAutoGeneratedKey
	public String getProfId() {
		return profId;
	}

	public void setProfId(String profId) {
		this.profId = profId;
	}
	@DynamoDBAttribute(attributeName="firstName")
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	@DynamoDBAttribute(attributeName="department")
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}	
	@DynamoDBAttribute(attributeName="joiningDate")
	public String getJoiningDate() {
		return this.joiningDate;
	}
	public void setJoiningDate(String joiningDate) {
		this.joiningDate = joiningDate;
	}
	

}