package com.csye6225.spring2020.courseservice2.Model;

import java.util.ArrayList;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName="Program")
public class Program {
	private String programId;
	private String name;
	private List<String> courseList;

	public Program() {

	}

	public Program(String name) {
		this.name = name;
		this.courseList = new ArrayList();
	}
	@DynamoDBHashKey(attributeName="programId")
	@DynamoDBAutoGeneratedKey
	public String getProgramId() {
		return programId;
	}

	public void setProgramId(String programId) {
		this.programId = programId;
	}
	@DynamoDBAttribute(attributeName = "programName")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@DynamoDBAttribute(attributeName = "courses")
	public List<String> getCourseList() {
		if (courseList == null) {
			courseList = new ArrayList();
		}
		return courseList;
	}

	public void setCourseList(List<String> courseList) {
		this.courseList = courseList;
	}
}