package com.csye6225.spring2020.courseservice2.Model;

import java.util.ArrayList;
import java.util.List;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName="Student")
public class Student {
	private String studentId;
	private String id;
	private String firstName;
	private String lastName;
	private List<String> courseName;
	private String program;
	private String image;
	
	public Student() {
		
	}
	
	public Student(String firstName, String lastName,String image) {
		this.id = firstName + lastName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.courseName = new ArrayList<>();
		this.image = image;
		
	}
	@DynamoDBHashKey(attributeName="studentId")
	@DynamoDBAutoGeneratedKey
	public String getStudentId() {
		return studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}
	@DynamoDBAttribute(attributeName = "programName")
	public String getProgram() {
		return program;
	}

	public void setProgram(String program) {
		this.program = program;
	}
	@DynamoDBAttribute(attributeName = "image")
	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}
	@DynamoDBAttribute(attributeName = "id")
	public String getId() {
		return firstName+lastName;
	}

	public void setId(String id) {
		this.id = id;
	}
	@DynamoDBAttribute(attributeName = "firstName")
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	@DynamoDBAttribute(attributeName = "lastName")
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	@DynamoDBAttribute(attributeName = "courses")
	public List<String> getCourses() {
		if(this.courseName == null) {
			this.courseName = new ArrayList<>();
		}
	
		return courseName;
	}

	public void setCourses(List<String> courses) {
		this.courseName = courses;
	}
	
}
